name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Gera a animação Snake
      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: gaab-braga
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz o commit e envia o arquivo para o branch
      - name: Push generated SVG to the `main` branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
