name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Generate Snake animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: gaab-braga  
          outputs: dist/snake.svg do

      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Generated snake animation"
          git push

